name: health_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  calendar_view: ^1.2.0
  cell_calendar: ^0.8.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  easy_sidemenu: ^0.6.0
  expandable_datatable: ^0.0.7
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  panara_dialogs: ^0.1.5
  pluto_grid_plus: ^8.4.2
  scrollable_table_view: ^2.0.3
  syncfusion_flutter_calendar: ^26.2.13
  syncfusion_flutter_charts: ^26.2.11
  syncfusion_flutter_datagrid: ^26.2.11
  toastification: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/


